### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by quantatanu** [kordosky/rock_propagation#3]
Hi,

I have a few questions:

1. ``gNtpConvDUNE.cxx`` line # ``2885``   ``if( parser.OptionExists('f') )`` and ``-i`` specifies the input file path, but according to the instructions ``runRockPropagation`` takes input file name through ``-f``. How do we specify the output file format then? 

2. Also, ``gNtpConvDUNE.cxx`` says that for for ``RooTracker`` output, ``-t`` must be passed too in order to avoid ``segfault``, do we need this also for ``t2k_rootracker``?

Thanks

**Comment by quantatanu** [comment]
Or, I think "gNtpConvDUNE.cxx" is just a separate converter.

**Comment by kordosky** [comment]
gNtpConvDUNE.cxx makes a version of the GENIE gntpc with a small modification to greatly increase the size of the static arrays in the output.

**Comment by quantatanu** [comment]
Thanks
